language: ruby
cache:
  apt: true
  directories:
    - vendor/bundle
    - $HOME/.cache/pip
python:
  - 2.7
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - jruby
before_install:
  - gem update --system
  - gem --version
  - gem install bundler
  - sudo apt-get update -qq
install:
  - sudo apt-get install -qq graphviz
  - sudo apt-get install -qq python-gtk2
  - sudo pip install blockdiag actdiag seqdiag nwdiag
  - sudo pip install shaape
  - bundle install --path vendor/bundle --jobs=3 --retry=3
  - npm install -g mermaid
  - npm install -g wavedrom-cli
  - sudo apt-get install -qq imagemagick
