---
version: "{build}"
branches:
  only:
    - master
clone_depth: 10
install:
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  # https causes certificate verification errors
  # Updating rubygems resolves this, but then gem install seems to hang for unknown reasons
  # Use http instead as a workaround
  # - gem update --system
  - gem sources -r https://rubygems.org/
  - gem sources -a http://rubygems.org/
  - gem install bundler --no-ri --no-rdoc
  - bundle install
  - cinst graphviz.portable
build_script:
  - bundle exec rake package
test_script:
  - bundle exec rake test
artifacts:
  - path: pkg\*.gem

environment:
  matrix:
    - ruby_version: "193"
    - ruby_version: "200"
    - ruby_version: "200-x64"
    - ruby_version: "21"
    - ruby_version: "21-x64"
