---
version: "{build}"
branches:
  only:
    - master
clone_depth: 10
install:
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - gem update --system --quiet
  - gem install bundler --no-ri --no-rdoc
  - bundle install
  - cinst graphviz.portable
build_script:
  - rake package
test_script:
  - rake test
artifacts:
  - path: pkg\*.gem

environment:
  matrix:
    - ruby_version: "193"
    - ruby_version: "200"
    - ruby_version: "200-x64"
    - ruby_version: "21"
    - ruby_version: "21-x64"